/*
 * Soil_Moisture_priv.h
 *
 */

#ifndef HAL_SOIL_MOISTURE_SENSOR_SOIL_MOISTURE_PRIV_H_
#define HAL_SOIL_MOISTURE_SENSOR_SOIL_MOISTURE_PRIV_H_


#endif /* HAL_SOIL_MOISTURE_SENSOR_SOIL_MOISTURE_PRIV_H_ */
